# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - ./tinystream.py
      - ./test/**
      - requirements.txt
  pull_request:
    branches: [ "main" ]
    paths:
      - ./tinystream.py
      - ./test/**
      - requirements.txt

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: "pip"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Test with pytest
      env:
        PYTHONPATH: "."
      run: |
        pytest --junitxml=./test-results/tests.xml --cov=./tinystream.py -n 4 ./tests/
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          test-results/**/*.xml
    - name: Generate coverage report
      run: coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      continue-on-error: true
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        #fail_ci_if_error: true
        files: ./coverage.xml
        verbose: true
